# Generated by Django 3.2.6 on 2022-01-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excert',
            new_name='excerpt',
        ),
    ]
